### ISSUE TITLE
 [Question] Is it possible to get the bitmap of a hidden window?

### ISSUE THREAD

**Issue by jpuerj** [iseahound/ImagePut#18]
Is there any workaround to get the bitmap of a hidden window? When I hide the window I get a full blank bitmap...

**Comment by iseahound** [comment]
Maybe. Chances are that it may be possible to intercept a WM_PAINT message, but it would be limited to windows that don't use hardware acceleration (DirectX), and it would very likely not work on modern versions of Windows, since hiding windows and copying sensitive information is now a thing. 

In short, I will only provide support for publicly available APIs.
